/* =====================================================================
   FATE/STAY LAST TIME 2.0  —  CONTENT DATABASE
   ---------------------------------------------------------------------
   Zero-terminal, no-build architecture. To publish a new chapter you only
   need to edit this plain text file. Save it and refresh the page.

   HOW TO ADD A CHAPTER:
     1. Copy one of the { ... } blocks below.
     2. Give it a new unique `id` (use the next number in sequence).
     3. Edit the title / volume / synopsis.
     4. Build the `content` array using the three building blocks:

        { type: "prose",    text: "..." }
            -> Standard narration. Soft margins, comfortable pacing.

        { type: "dialogue", speaker: "Name", text: "...", variant: "cyan" }
            -> A visual-novel dialogue frame. `variant` sets the neon accent:
               "cyan" (ally/hero), "crimson" (hostile/villain), "neutral".

        { type: "impact",   text: "...", effect: "shake" }
            -> A kinetic distortion element. `effect` can be:
               "shake" (crimson hardware-shake), "glow" (pulsing cyan),
               "expand" (breathing scale).

   KEYWORDS below are auto-highlighted wherever they appear in prose or
   dialogue (Noble Phantasms, artifacts, etc.).
   ===================================================================== */

const VOLUMES = {
  1: {
    "numeral": "I",
    "title": "The Catalyst"
  },
  2: {
    "numeral": "II",
    "title": "The Summoning"
  },
  3: {
    "numeral": "III",
    "title": "War of the Grail"
  },
  4: {
    "numeral": "IV",
    "title": "The Global War"
  },
  5: {
    "numeral": "V",
    "title": "The Clock Tower Descent"
  }
};

const KEYPHRASES = [
  "Holy Grail",
  "Command Seal",
  "Noble Phantasm",
  "Reality Marble",
  "Trace On",
  "Trace — On",
  "Gate of Babylon",
  "Rho Aias",
  "Unlimited Blade Works",
  "Excalibur",
  "Prana Burst"
];

const CHAPTERS = [

  /* ============================ CHAPTER 1 ============================ */
  {
    id: 1,
    title: "The Flap of the Leather",
    volume: 1,
    synopsis: "A shoe breaks at a wedding. A cousin films it. A billion people laugh. And in a Ludhiana basement, something ancient answers a call it should never have heard.",
    content: [
      { type: "prose", text: "The shoe broke at exactly 11:43 PM." },
      { type: "prose", text: "I was standing near the buffet table, shifting my weight to avoid a cluster of guests I didn't know. The marble floor was polished to a mirror sheen. When I lifted my right heel, the golden jutti — brand new, heavily embroidered, purchased from a vendor who had sworn on his mother's life that the leather was genuine — separated from its sole with a sound like a dry branch snapping." },
      { type: "prose", text: "And for one strange, electric second, something shifted." },
      { type: "prose", text: "Not in the room. In me. A cold prickle swept up my spine, the kind of static shock you get from a car door in winter. The air in my lungs felt too thin, too sharp, as if the world had briefly unzipped and let something leak through. The hair on my arms stood up." },
      { type: "prose", text: "Then the moment passed. I was just a man with a broken shoe." },
      { type: "prose", text: "Slide the foot. Don't lift it. Just slide." },
      { type: "prose", text: "I took a shuffling step toward the catering exit. The detached sole struck the marble." },
      { type: "impact", effect: "shake", text: "SLAP." },
      { type: "prose", text: "The acoustics of the banquet hall turned that single, pathetic sound into a gunshot. Conversations faltered. Heads turned. The DJ's bass line thumped into the sudden silence like a heartbeat." },
      { type: "impact", effect: "shake", text: "SLAP. SLAP." },
      { type: "prose", text: "I kept moving, my face burning. The ruined shoe flapped against the bottom of my foot with every step, loud and wet and ridiculous. I was fifteen feet from the exit when my cousin stepped into my path." },
      { type: "prose", text: "Alistair Vane." },
      { type: "prose", text: "He was everything I was not — tall where I was average, loud where I was quiet, magnetic in the way that only people who have never questioned their own worth can be. He had come from abroad for the wedding, the prodigal grandson returning to Punjab with a London accent and a suitcase full of expensive gifts. The guests adored him. They had been adoring him all evening." },
      { type: "prose", text: "He held a plate of paneer tikka in his left hand. In his right, raised to eye level, was his phone. The camera lens pointed directly at my foot." },
      { type: "prose", text: "His grin was so wide it looked like it hurt." },
      { type: "dialogue", speaker: "Alistair", variant: "crimson", text: "“Gurtej. Oh, man. This is absolute cinema.”" },
      { type: "prose", text: "The red recording light blinked on." },
      { type: "dialogue", speaker: "Gurtej", variant: "neutral", text: "“Alistair. Delete it.”" },
      { type: "prose", text: "He didn't. He stepped closer, angling down to capture the full tragedy — the dangling sole, the exposed toes, the frozen horror on my face. Behind him, two of his friends were already pulling out their own phones, laughing. Their laughter had the same careless, polished quality as Alistair's accent. Expensive laughter." },
      { type: "dialogue", speaker: "Alistair", variant: "crimson", text: "“Walk, bro! Come on, take a step. Let the people see the swagger.”" },
      { type: "prose", text: "I didn't walk. I stood there, one foot bare on the freezing marble, while my cousin filmed me for forty-three seconds. Then I turned and limped out through the catering door into the service corridor." },
      { type: "prose", text: "Behind me, I heard him laughing. I heard his friends laughing. I heard someone — maybe a guest, maybe a stranger — ask what was so funny." },
      { type: "prose", text: "By the time I reached my car, the video was already uploaded. Alistair had tagged me. He had added a caption: \"When the jutti costs more than the degree 😂👞💀\"" },
      { type: "prose", text: "He had also added a poll: \"Rate my cousin's walk\" — with options ranging from \"Penguin\" to \"Full Send\" to \"Absolutely Cooked.\"" },
      { type: "prose", text: "I sat in the driver's seat, one shoe still on, one foot bare, and stared at the glowing screen. The notifications had already started. Likes. Comments. Shares. A stranger from Mumbai had commented: Bro moving like a NPC in a Bethesda game 💀" },
      { type: "prose", text: "I turned off the phone. I drove home." },
      { type: "impact", effect: "expand", text: "THE MORNING AFTER" },
      { type: "prose", text: "The next morning, the video had 47,000 views." },
      { type: "prose", text: "By noon, someone had edited it — adding cartoon sound effects over each slap of the sole, freeze-framing my face at the moment of impact, zooming in on my exposed toes with a slow-motion replay and a bass-boosted fart noise. That version had 120,000 views by the time I finished lunch." },
      { type: "prose", text: "I called Alistair at 1 PM." },
      { type: "dialogue", speaker: "Gurtej", variant: "neutral", text: "“Hey. Take it down.”" },
      { type: "dialogue", speaker: "Alistair", variant: "crimson", text: "“Bro, it's just a joke. Everyone's loving it. Did you see the comments? Someone called you 'Lord Flapinton.' That's comedy gold.”" },
      { type: "dialogue", speaker: "Gurtej", variant: "neutral", text: "“Alistair. I'm serious. Take it down.”" },
      { type: "prose", text: "A pause. I could hear him chewing something." },
      { type: "dialogue", speaker: "Alistair", variant: "crimson", text: "“I'll think about it.”" },
      { type: "prose", text: "He hung up." },
      { type: "prose", text: "I called again at 3 PM. No answer. At 5 PM, I texted him: Please. This is getting out of hand. He replied with a laughing emoji and a link to the video's analytics page. 340,000 views. He had monetized it." },
      { type: "prose", text: "I sat in my apartment — the small one-bedroom I had rented after moving out of the hostel, the one with the bare walls and the single window that faced a brick wall three feet away — and stared at my dual monitors. On the left screen: the video, now at 520,000 views, the view counter ticking upward in real time. On the right: the half-finished outline for Chapter 12 of my web novel. A story about gods and rankings and power earned through struggle. I had spent three years writing it. Three years building a world where effort meant something." },
      { type: "prose", text: "But it wasn't just a story." },
      { type: "prose", text: "Some of the things I had written — the summoning circles, the sympathetic resonance between objects and power, the mechanics of conceptual weight — felt too real. I had found fragments of them in old forums, in archived manuscripts scanned from university libraries, in dark web repositories that claimed to preserve pre-Christian magical traditions. I had passed it off as \"research\" for my novel. I had convinced myself it was all fiction." },
      { type: "prose", text: "But deep down, I had always wondered. And the electric prickle I had felt when the shoe broke… that had not been fictional." },
      { type: "prose", text: "Neither screen brought me any comfort." },
      { type: "prose", text: "I closed both tabs. I opened a new one and started researching how to file a takedown request." },
      { type: "impact", effect: "expand", text: "THE REJECTION" },
      { type: "prose", text: "The takedown request was rejected the following morning." },
      { type: "prose", text: "Alistair had filed a counter-notice within hours. The video, he argued, was \"transformative content\" — his editing, his commentary, his additions qualified as fair use under international copyright law. The platform agreed. The decision was final. No further appeals would be considered." },
      { type: "prose", text: "I read the rejection email three times. Then I sat through a Google Meet for my BBA project group, my camera off, my microphone muted. When I finally unmuted to present my section on financial modeling, someone in the call — a stranger, from a different section entirely — typed into the public chat:" },
      { type: "impact", effect: "glow", text: "Bro walk like a penguin fr fr 🐧" },
      { type: "prose", text: "Three people laughed before the professor muted the chat. The professor did not reprimand the student. The professor did not ask if I was okay. The professor simply muted the chat and said, \"Continue with your presentation, Gurtej.\"" },
      { type: "prose", text: "I continued. I finished my section. I thanked the group. I left the call." },
      { type: "prose", text: "The video had 1.2 million views." },
      { type: "prose", text: "Someone had made a reaction video — a popular influencer, two million subscribers, watching my humiliation with his mouth open in exaggerated shock, pausing every few seconds to wheeze with laughter. Someone else had made a compilation: \"Top 10 Wedding Fails of 2024.\" My shoe was number three." },
      { type: "prose", text: "I texted Alistair again." },
      { type: "prose", text: "Can we at least talk? In person?" },
      { type: "prose", text: "This time, he called me." },
      { type: "dialogue", speaker: "Alistair", variant: "crimson", text: "“Bro, I've made roughly eight lakhs in ad revenue so far. You want a cut? I'll give you ten percent. That's fair, right? You're the star.”" },
      { type: "dialogue", speaker: "Gurtej", variant: "neutral", text: "“I don't want money. I want the video gone.”" },
      { type: "dialogue", speaker: "Alistair", variant: "crimson", text: "“Gone? Bro, it's at 1.2 million. Even if I delete it right now — right this second — people have already ripped it. Re-uploaded it. It's on other platforms. It's in group chats. It's a meme now. Why don't you just lean into it? Make your own video. Do the walk. Own the joke. You could monetize too.”" },
      { type: "dialogue", speaker: "Gurtej", variant: "neutral", text: "“I don't want to own the joke. I want my life back.”" },
      { type: "dialogue", speaker: "Alistair", variant: "crimson", text: "“Your life? Bro, it's a shoe. You tripped. People laughed. In a week, no one will remember. You're acting like I ruined your life over a shoe.”" },
      { type: "prose", text: "I didn't answer." },
      { type: "dialogue", speaker: "Alistair", variant: "crimson", text: "“Look, I'll think about taking it down. Okay? I'll think about it. Just… stop being so dramatic.”" },
      { type: "prose", text: "He hung up." },
      { type: "prose", text: "I sat in the dark, my phone buzzing with notifications I didn't open. Somewhere in Ludhiana, my cousin was counting his money. Somewhere in the world, a million strangers were laughing at the flap of cheap leather against a marble floor." },
      { type: "prose", text: "There was no one to call. No one who would understand. The silence of the apartment was total. The walls had never felt so close." },
      { type: "prose", text: "I opened my browser again. I navigated to the dark web forum where I had found the manuscript fragments. The post was still there: \"On the Creation of Pseudo-Spiritron Anchors via Conceptual Resonance.\" I had read it a dozen times. I had used parts of it for my novel. But I had never considered that it might be real." },
      { type: "prose", text: "Now I read it again. And this time, I noticed something I had missed before. A footnote. A reference to a specific leyline convergence point." },
      { type: "impact", effect: "glow", text: "…such convergences are rare, but the sub-Himalayan basin, particularly beneath the ancient city of Ludhiana, contains a dormant confluence of no fewer than seven minor ley arteries. A ritual performed at this location, powered by sufficient conceptual weight, could theoretically bypass the need for traditional circuits, utilizing the leyline itself as the energy source…" },
      { type: "prose", text: "Ludhiana. My city. The city where the wedding had happened. The city where the shoe had broken." },
      { type: "prose", text: "And the basement of my apartment building — the unfinished sub-level that no one ever used, the room I had accidentally received a key for — was directly below me." },
      { type: "prose", text: "I didn't sleep that night. I read." },
      { type: "impact", effect: "expand", text: "TEN MILLION" },
      { type: "prose", text: "On the fourth day, the video hit 10 million views." },
      { type: "prose", text: "I left the apartment. I drove to the campus, not because I had class — I had stopped attending — but because I needed to walk somewhere that wasn't my bedroom. I needed to move, to breathe, to exist in a space where no one was looking at me." },
      { type: "prose", text: "Someone had printed a screenshot of my frozen, terrified face — mouth half-open, one foot bare, the golden sole dangling like a dead fish — and taped it to the notice board outside the Business Studies wing. Underneath, in black Sharpie: \"PENGUIN WALK CHALLENGE — SIGN UP HERE — WINNERS GET FREE JUTTIS.\"" },
      { type: "prose", text: "I tore it down. I walked back to my car. I drove home." },
      { type: "prose", text: "That evening, I sat in the basement. Cold. Damp. Completely silent. The concrete walls were unpainted. The floor was dusty and cracked. No notifications reached down here. No laughter." },
      { type: "prose", text: "Just me. The dark. The dust." },
      { type: "prose", text: "And the golden jutti, still in my hand." },
      { type: "prose", text: "I had kept it. I didn't know why at the time. But now, under the single bare bulb, I turned the ruined leather over and over, and I finally understood what I was looking at." },
      { type: "prose", text: "The embroidery on the jutti — the swirling golden patterns I had thought were just traditional Punjabi designs — was not random. I had seen those exact patterns before. They were in one of the manuscripts I had downloaded months ago, a scanned copy of a 17th-century text on Indian magecraft. The author had called them Diksha Sutras — \"initiation threads\" — a summoning mandala disguised as decoration, woven into clothing to hide it from the Clock Tower's enforcers. A catalyst, waiting to be activated." },
      { type: "prose", text: "The shoe had not been a random purchase. The vendor who sold it to me had said it was \"very special.\" I had thought he was haggling. But he had meant something else. Perhaps he was a descendant of the tradition. Perhaps he didn't even know what he was selling. Either way, the catalyst had been on my foot for an entire evening, and when it broke — when it was humiliated, when it was seen by millions, when a billion eyes focused their attention on the flap of cheap leather against marble — it had charged." },
      { type: "prose", text: "Conceptual weight. The principle that an object, properly prepared, could serve as a bridge between worlds." },
      { type: "prose", text: "The shoe had been seen by millions. It had been laughed at, shared, mocked, monetized, edited, remixed, reposted. It carried the attention of the planet. It carried four days of my humiliation." },
      { type: "prose", text: "And the leyline beneath this basement was waiting." },
      { type: "prose", text: "I had spent three years writing a web novel about gods and warriors and the systems that ranked them. I had spent three years pretending the research was just for fiction. But the electric shock I had felt at the wedding — the cold, sharp awareness — had not been fiction. It had been my own dormant circuits, responding to a Mystery for the first time. I had no Crest. I had no lineage that I knew of. But I had something that the manuscript called Samskara — a latent spiritual potential, passed down through certain bloodlines in the subcontinent, ignored by the Clock Tower, forgotten even by the families that carried it." },
      { type: "prose", text: "I had a ruined shoe. I had a pocketknife. I had my own blood." },
      { type: "prose", text: "I had four days of failure. And beneath the failure — beneath the humiliation and the exhaustion and the creeping, hollow silence where my old self used to live — I had something that felt, for the first time in my life, like absolute certainty." },
      { type: "prose", text: "The basement floor was dusty concrete." },
      { type: "prose", text: "I knelt down. I opened the pocketknife. The blade caught the faint light from the single bulb overhead. I pressed the edge to my left palm, feeling the sting of cold steel." },
      { type: "prose", text: "If the manuscript was right, if the leyline was real, if the catalyst was charged, then I could summon something. I didn't know what. The catalyst's pattern was generic — it would attract a Heroic Spirit who resonated with humiliation, with vengeance, with the destruction of an old world. That was enough." },
      { type: "prose", text: "I didn't need chalk. I didn't need mercury. The leyline would serve as the foundation. My blood would serve as the contract." },
      { type: "prose", text: "Tomorrow, the world would begin to end. But tonight, I just wanted to see if anything would answer." }
    ]
  },

  /* ============================ CHAPTER 2 ============================ */
  {
    id: 2,
    title: "Blood and the Catalyst",
    volume: 2,
    synopsis: "A blood-drawn circle in a dusty basement calls forth two Heroic Spirits. No Command Seals. No Holy Grail. Just a Master with a grudge and a contract built on conviction alone.",
    content: [
      { type: "impact", effect: "expand", text: "HOUR 13 TO 14: THE ARCHITECTURE OF VENGEANCE" },
      { type: "prose", text: "The basement beneath my house was a relic of unfinished construction, a cavern of exposed brick, dusty concrete, and the lingering smell of damp earth. Down here, the world felt distant. The incessant buzzing of my phone, the notifications, the billion pairs of eyes — none of it could penetrate the concrete." },
      { type: "prose", text: "I knelt in the center of the floor. My hands were shaking, not from fear, but from a profound, chilling exhaustion." },
      { type: "prose", text: "The catalyst lay before me: the ruined golden jutti, now an artifact imbued with the conceptual weight of absolute humiliation. I didn't have liquid mercury or crushed gems. I had myself. I pressed the pocketknife to my palm and let the blood drip onto the dusty concrete, dragging my finger to draw the summoning circle — the logic of web architecture married to the chaotic lines of an arcane array." },
      { type: "impact", effect: "shake", text: "\"Let silver and steel be the essence. Let stone and the archduke of contracts be the foundation. Let rise a wall against the wind that shall fall. Let the four cardinal gates close. Let the three-forked road from the crown reaching unto the Kingdom rotate.\"" },
      { type: "prose", text: "The blood on the concrete glowed — faint, sickly red. The single lightbulb hanging from the ceiling flickered, then shattered." },
      { type: "impact", effect: "shake", text: "\"An oath shall be sworn here! I shall attain all virtues of all of Heaven. I shall have dominion over all evils of all of Hell. From the Seventh Heaven, attended to by three great words of power... Come forth from the ring of deterrence, Protector of the Holy Balance!\"" },
      { type: "impact", effect: "expand", text: "HOUR 15: THE MANIFESTATION OF MYTH" },
      { type: "prose", text: "The explosion of mana shook the foundation of the house. A blinding pillar of azure and crimson light erupted from the circle. As it faded, two figures stood within the blood-drawn boundary." },
      { type: "prose", text: "The first was a woman clad in silver armor over a dress of deep royal blue, golden hair tied back, emerald eyes locked onto mine with sovereign intensity. An invisible blade masked by swirling wind rested in her grip. Artoria Pendragon. Saber. The King of Knights." },
      { type: "prose", text: "Beside her stood a man forged in a dying star — dark breastplate, crimson shroud, steel-gray eyes scanning the basement with the cold calculation of a veteran assassin. EMIYA. Archer. The Wrought Iron Hero." },
      { type: "dialogue", speaker: "Saber", variant: "cyan", text: "“I ask of you. Are you my Master?”" },
      { type: "dialogue", speaker: "Gurtej", variant: "neutral", text: "“I am.”" },
      { type: "dialogue", speaker: "Archer", variant: "cyan", text: "“A dual summon. And with a catalyst dripping in such... pathetic resonance. No Command Seals on your hand, Master. No Holy Grail in sight. Just a basement and a broken shoe. Tell me, what exactly have you dragged us into?”" },
      { type: "impact", effect: "expand", text: "HOUR 16 TO 18: THE BRIEFING OF THE VIRAL WAR" },
      { type: "dialogue", speaker: "Gurtej", variant: "neutral", text: "“There is no Holy Grail. Not here. There are no other Masters. There is no Clock Tower oversight.”" },
      { type: "dialogue", speaker: "Saber", variant: "cyan", text: "“Then why have we been called from the Throne of Heroes? A Heroic Spirit is a weapon of humanity's defense. If there is no war, if there is no threat to the Human Order...”" },
      { type: "dialogue", speaker: "Gurtej", variant: "neutral", text: "“The Human Order is the threat.”" },
      { type: "prose", text: "I brought up the video on my phone. The analytics. The comments." },
      { type: "dialogue", speaker: "Gurtej", variant: "neutral", text: "“Thirteen hours ago, my shoe broke at a wedding. My cousin recorded it. Right now, over one billion people are watching it. They are laughing. He is making a fortune off of my absolute humiliation. My life, my future, my dignity — it was all erased for a joke.”" },
      { type: "dialogue", speaker: "Saber", variant: "cyan", text: "“A moving picture, sent across the world? And this 'billion' people mock you for a failure of equipment? Where is the honor in this? Where is the challenge?”" },
      { type: "dialogue", speaker: "Archer", variant: "cyan", text: "“There is none. It's an algorithmic slaughter. A digital crucifixion. You didn't summon us to fight a Magus, Master. You summoned us to fight a server farm. You want us to kill a meme.”" },
      { type: "dialogue", speaker: "Gurtej", variant: "neutral", text: "“No. I want you to kill the world that made it.”" },
      { type: "impact", effect: "expand", text: "HOUR 19 TO 24: THE CONTRACT OF ERASURE" },
      { type: "dialogue", speaker: "Saber", variant: "cyan", text: "“You ask me to destroy the innocent because the guilty walk among them? That is not justice, Master. That is a massacre. I am a Knight. I will not turn my blade against humanity over a wounded pride.”" },
      { type: "dialogue", speaker: "Gurtej", variant: "neutral", text: "“Are they innocent? A billion people watched a man's dignity burn and turned it into entertainment. Not one person in a billion said 'stop.' Silence in the face of cruelty is complicity. Camelot didn't fall because of one traitor. It fell because the rest of the kingdom watched it happen.”" },
      { type: "prose", text: "Saber flinched — barely perceptible, a tightening of the jaw. I had found the crack in the armor of the King." },
      { type: "dialogue", speaker: "Archer", variant: "cyan", text: "“A compelling argument, Master. But there is a mechanical flaw. Look at your hand. No Command Seals. No enforcement mechanism. If Saber or I decide to walk away right now, there is nothing binding us to you.”" },
      { type: "dialogue", speaker: "Gurtej", variant: "neutral", text: "“Then walk.”" },
      { type: "dialogue", speaker: "Archer", variant: "cyan", text: "“...A contract of conviction rather than compulsion. How absurdly idealistic. Fine. I've followed worse reasons to the end of the world.”" },
      { type: "dialogue", speaker: "Saber", variant: "cyan", text: "“If this world has truly abandoned its honor... I will be your sword, Gurtej. But know this — if I find even one soul worth saving before the end, I will stay my blade.”" },
      { type: "dialogue", speaker: "Gurtej", variant: "neutral", text: "“First, we blind them. Archer, you are going to rip the cousin's digital empire to shreds. You are going to burn his servers to the ground.”" },
      { type: "impact", effect: "glow", text: "The 70-hour timer ticked down. Hour 24. The counter-attack had begun." }
    ]
  },

  /* ============================ CHAPTER 3 ============================ */
  {
    id: 3,
    title: "The Ghost in the Machine",
    volume: 3,
    synopsis: "Archer turns the global internet into a battlefield, erasing a fortune in an instant. But burning a digital empire draws hunters far older than the web.",
    content: [
      { type: "impact", effect: "expand", text: "HOUR 25 TO 28: STRUCTURAL GRASP AND THE DIGITAL FORGE" },
      { type: "prose", text: "We abandoned the basement and moved upstairs to my bedroom, the nerve center of my previous, quiet life. My room, usually a sanctuary for web development and writing The Gods Rank Awakening, now served as the war room for the end of the world." },
      { type: "dialogue", speaker: "Archer", variant: "cyan", text: "“A crude forge. But the underlying principle of a network is no different from the leylines of a territory. It is all just pathways of energy.”" },
      { type: "dialogue", speaker: "Gurtej", variant: "neutral", text: "“Can you trace it?”" },
      { type: "prose", text: "Archer reached out his tanned, scarred hand and placed it flat against the side of the PC casing." },
      { type: "impact", effect: "shake", text: "\"Trace On.\"" },
      { type: "prose", text: "Faint, glowing green circuits crawled up his arm. His Structural Grasp comprehended the entire history, composition, and conceptual purpose of anything he touched — right now, the architecture of the modern internet." },
      { type: "impact", effect: "glow", text: "1,104,560,000 views — FROZEN" },
      { type: "dialogue", speaker: "Archer", variant: "cyan", text: "“I have located the primary server nodes hosting the visual data. And I have traced the financial conduits. The 'Mora' he has gathered... it flows through a dozen digital banks.”" },
      { type: "dialogue", speaker: "Gurtej", variant: "neutral", text: "“Burn it.”" },
      { type: "dialogue", speaker: "Archer", variant: "cyan", text: "“With pleasure.”" },
      { type: "prose", text: "He didn't inject prana into the software — raw magical energy and modern electronics despise each other. Instead he used Structural Grasp to comprehend the physical architecture of the network, then manipulated the components at the molecular level: forcing capacitors to overload, cooling fans to seize, hard drive platters warped by microscopic margins. He wasn't hacking the code; he was assassinating the hardware." },
      { type: "impact", effect: "glow", text: "Revenue: $140,000 → $0.00 · Crypto Wallets: ERASED · Ad-Sense: TERMINATED" },
      { type: "impact", effect: "expand", text: "HOUR 29 TO 32: THE PANIC AND THE MERCENARIES" },
      { type: "prose", text: "I opened my phone. My cousin was live from an upscale hotel room, laughing with his viewers, when his expression faltered." },
      { type: "dialogue", speaker: "Alistair", variant: "crimson", text: "“Wait, what?”" },
      { type: "prose", text: "The live chat flooded with confusion. He picked up a secondary phone, breathing fast." },
      { type: "dialogue", speaker: "Alistair", variant: "crimson", text: "“No, no, no... the bank app is down. Everything is... it says zero.”" },
      { type: "prose", text: "I watched sheer, unadulterated terror wash over the man who had ruined my life. It was intoxicating. But a rat backed into a corner will always bite." },
      { type: "prose", text: "He ended the stream and made a frantic call to the dark web — connections he'd bragged about at family gatherings — believing he was under a coordinated cyber-attack. He hired a PMC, a Private Military Company operating off the books." },
      { type: "prose", text: "But there was a complication he didn't foresee. The Clock Tower had orbital satellites and leyline monitors. They had detected the massive surge of True Ether from my basement. They intercepted my cousin's PMC contract. They weren't coming for his money; they were coming to secure the Master who had illegally summoned Heroic Spirits." },
      { type: "dialogue", speaker: "Saber", variant: "cyan", text: "“Master. We are no longer alone.”" },
      { type: "impact", effect: "expand", text: "HOUR 33 TO 36: THE SIEGE OF LUDHIANA" },
      { type: "prose", text: "It was 2:00 AM. Four matte-black SUVs rolled down my narrow street, headlights extinguished, boxing my house in at the four corners." },
      { type: "dialogue", speaker: "Archer", variant: "cyan", text: "“Tactical operatives. Armed with modern kinetic weapons. But there are others. Three distinct prana signatures. Magi. Clock Tower hounds.”" },
      { type: "prose", text: "A bounded field was thrown over my house, cutting off all sound from the outside world." },
      { type: "impact", effect: "shake", text: "CRASH." },
      { type: "prose", text: "The front door was blown off its hinges. Flashbangs filled the living room with blinding light. Six PMC operatives stormed in, rifles raised." },
      { type: "prose", text: "Saber didn't use the stairs. She plummeted straight through my bedroom floor to land in the center of the living room. The operatives opened fire." },
      { type: "impact", effect: "shake", text: "BRRRRRRT!" },
      { type: "prose", text: "But the bullets never touched her. Invisible Air deflected every round harmlessly into the walls. In less than three seconds, all six men were unconscious on the floor." },
      { type: "dialogue", speaker: "Saber", variant: "cyan", text: "“The vanguard is subdued.”" },
      { type: "prose", text: "Then the front wall of my living room simply dissolved. Three Clock Tower Enforcers stepped through the rubble, holding staves and jeweled daggers humming with stored magical energy." },
      { type: "dialogue", speaker: "Enforcer", variant: "crimson", text: "“Surrender the Servants, boy. You are an unregistered anomaly. By order of the Mage's Association, this territory is forfeit.”" },
      { type: "dialogue", speaker: "Gurtej", variant: "neutral", text: "“They don't understand, do they?”" },
      { type: "dialogue", speaker: "Archer", variant: "cyan", text: "“Magi rarely do. They think they are dealing with a rogue spellcaster. They don't realize they are standing on ground zero of a timeline erasure.”" },
      { type: "impact", effect: "glow", text: "The clock struck Hour 36. The digital war was over. The physical war had begun." }
    ]
  },

  /* ============================ CHAPTER 4 ============================ */
  {
    id: 4,
    title: "The Hunt and the High-Altitude Fortress",
    volume: 3,
    synopsis: "A convoy through the Himalayas, a mother's call left unanswered, and the gates of a coward's fortress about to fall.",
    content: [
      { type: "impact", effect: "expand", text: "HOUR 37: THE DISPARITY OF MYTH" },
      { type: "prose", text: "The three Clock Tower Enforcers stood amidst the rubble. The lead Magus raised a staff carved from petrified wood, drawing ambient mana to freeze Saber in place — a spell that would have shattered a modern tank." },
      { type: "prose", text: "He didn't even finish the third stanza. From the shattered floorhole above, Archer released the bowstring. A crimson, twisted arrow struck the ground a millimeter in front of the Magus's boots and exploded with spatial distortion, shorting his magic circuits out completely." },
      { type: "prose", text: "The other two Enforcers lunged at Saber with jagged, curse-dripping blades." },
      { type: "dialogue", speaker: "Saber", variant: "cyan", text: "“You bring curses to a Knight's domain?”" },
      { type: "prose", text: "She kicked the floor with Prana Burst. The shockwave threw both Enforcers into the wall, unconscious before they registered what hit them. The battle for my house had lasted exactly forty-five seconds." },
      { type: "dialogue", speaker: "Saber", variant: "cyan", text: "“Master. The perimeter is secure. But more will come. The Mage's Association does not accept defeat lightly.”" },
      { type: "dialogue", speaker: "Gurtej", variant: "neutral", text: "“Let them come. We aren't staying.”" },
      { type: "impact", effect: "expand", text: "HOUR 38 TO 41: THE DEPARTURE" },
      { type: "dialogue", speaker: "Gurtej", variant: "neutral", text: "“Archer. The cousin's location?”" },
      { type: "dialogue", speaker: "Archer", variant: "cyan", text: "“I did. When his accounts zeroed out, he panicked. He used an encrypted satellite phone to activate a contingency — a high-altitude bunker deep in the Himalayas, near the border. Bought with offline funds.”" },
      { type: "dialogue", speaker: "Gurtej", variant: "neutral", text: "“He thinks altitude and concrete can save him. Saber, can you drive?”" },
      { type: "prose", text: "Saber ran a gauntleted hand along the hood of the abandoned PMC SUV. Thanks to her Riding skill, she understood its mechanical soul better than the engineers who built it." },
      { type: "dialogue", speaker: "Saber", variant: "cyan", text: "“It is a crude chariot. But it will suffice.”" },
      { type: "prose", text: "We tore out of my neighborhood. I didn't look back. We had 33 hours left and a world to end." },
      { type: "impact", effect: "expand", text: "HOUR 42 TO 45: THE ASCENT INTO THE COLD" },
      { type: "prose", text: "We drove north, the flat heat of Punjab giving way to the foothills, then the towering silhouettes of the Himalayas." },
      { type: "dialogue", speaker: "Saber", variant: "cyan", text: "“You are quiet, Master. Are you mourning the life you left behind?”" },
      { type: "dialogue", speaker: "Gurtej", variant: "neutral", text: "“No. I'm just realizing how fragile it all was. Everything I cared about — my reputation, my studies, my future — it was all destroyed by a broken shoe and a laugh. If a world's foundation is that brittle, it was never real to begin with.”" },
      { type: "dialogue", speaker: "Archer", variant: "cyan", text: "“A harsh judgment. But not an inaccurate one. Humanity has always built castles on sand. The only difference now is that they build them out of data. And data is so very easy to erase.”" },
      { type: "prose", text: "At Hour 44, my phone rang. Not a notification. An actual call. Caller ID: Mom." },
      { type: "prose", text: "I let it ring out. It rang again. Three missed calls in ninety seconds. I powered the phone down and dropped it into the cup holder." },
      { type: "dialogue", speaker: "Saber", variant: "cyan", text: "“That was someone important to you.”" },
      { type: "dialogue", speaker: "Gurtej", variant: "neutral", text: "“Everyone is important to someone. That doesn't make the timeline worth saving.”" },
      { type: "prose", text: "By Hour 45, the paved roads ended. We drove treacherous, snow-covered dirt paths hugging sheer drops." },
      { type: "dialogue", speaker: "Archer", variant: "cyan", text: "“We are approaching the coordinates. I sense a massive grid of thermal optics, motion sensors, and automated sentry guns. He has turned this mountain into a fortress.”" },
      { type: "dialogue", speaker: "Gurtej", variant: "neutral", text: "“Can you bypass the sensors?”" },
      { type: "dialogue", speaker: "Archer", variant: "cyan", text: "“I don't need to. Stealth is for assassins. We are an execution squad.”" },
      { type: "impact", effect: "expand", text: "HOUR 46 TO 48: THE GATES OF THE COWARD" },
      { type: "prose", text: "At Hour 48, we crested a ridge above a brutalist bunker half-buried in the mountain, blast doors sealed, turrets tracking our SUV." },
      { type: "dialogue", speaker: "Saber", variant: "cyan", text: "“Master. The defenses are entirely mechanical. There are no human souls manning those walls.”" },
      { type: "dialogue", speaker: "Gurtej", variant: "neutral", text: "“He trusts machines more than people. Archer. Take out their eyes.”" },
      { type: "impact", effect: "shake", text: "\"I am the bone of my sword.\"" },
      { type: "prose", text: "Archer projected Hrunting, the Hound of the Red Plains, nocked onto the bowstring, and aimed at the bunker's communications tower." },
      { type: "prose", text: "He released. The crimson streak crossed two miles in a fraction of a second, shattering the tower and severing the bunker's connection to the outside world. Every turret on the wall swiveled and opened fire." },
      { type: "dialogue", speaker: "Gurtej", variant: "neutral", text: "“Saber. Clear the path.”" },
      { type: "prose", text: "Saber leapt from the ridge, falling like a meteor toward the storm of bullets and the unbreakable blast doors." },
      { type: "impact", effect: "glow", text: "The timer ticked to Hour 49. The final siege had begun." }
    ]
  },

  /* ============================ CHAPTER 5 ============================ */
  {
    id: 5,
    title: "The Golden Bastard and the Forge of the Soul",
    volume: 3,
    synopsis: "A King's ransom, a rival Servant, and the Counter Guardian's answer written in a thousand blades.",
    content: [
      { type: "impact", effect: "expand", text: "HOUR 49: THE METEOR OF AVALON" },
      { type: "prose", text: "Saber's Prana Burst hit. The bullets died in the conceptual pressure of her aura, falling to the snow like dead insects. She placed both hands flat against the meter-thick blast doors." },
      { type: "dialogue", speaker: "Saber", variant: "cyan", text: "“Begone.”" },
      { type: "prose", text: "The steel groaned and blew inward, crumpling like tin foil. Silence descended, broken only by the howling wind." },
      { type: "dialogue", speaker: "Archer", variant: "cyan", text: "“The path is clear, Master. But the atmosphere... it has changed.”" },
      { type: "impact", effect: "expand", text: "HOUR 50 TO 52: THE DESCENT INTO THE ANOMALY" },
      { type: "dialogue", speaker: "Saber", variant: "cyan", text: "“This is not just a bunker. The ambient mana is too thick. It is pooling here. Consolidating.”" },
      { type: "dialogue", speaker: "Archer", variant: "cyan", text: "“The Lesser Grail. Master, your summoning in Ludhiana was a massive, unregistered spike of True Ether. You didn't just summon two Servants; you acted as a conceptual flare. You woke up the dormant ley lines of the Himalayas. The World is trying to correct the anomaly by initiating a localized Holy Grail War.”" },
      { type: "dialogue", speaker: "Gurtej", variant: "neutral", text: "“Meaning what?”" },
      { type: "dialogue", speaker: "Archer", variant: "cyan", text: "“Meaning the rules of engagement have changed. And a Grail requires multiple Masters.”" },
      { type: "impact", effect: "expand", text: "HOUR 53: THE SANCTUM OF VANITY" },
      { type: "prose", text: "At the far end of a vast, dead-monitor sanctum, my cousin sat in a plush leather chair — pale, sleep-deprived, but wearing a twisted, arrogant smirk." },
      { type: "dialogue", speaker: "Alistair", variant: "crimson", text: "“Gurtej. You actually came. You dragged a couple of cosplayers all the way to the top of the world because you couldn't handle a little joke.”" },
      { type: "dialogue", speaker: "Gurtej", variant: "neutral", text: "“The joke is over. Your servers are ashes. Your money is gone. The world is going to forget you ever existed. It's time to pay the toll.”" },
      { type: "prose", text: "He raised his right hand. Glowing on the back of it, burning crimson, were three Command Seals shaped like a golden chalice." },
      { type: "dialogue", speaker: "Alistair", variant: "crimson", text: "“You think you're the only one who can play this game? When my money started vanishing, I made a call to the dark web. A Magus in London was selling a relic — a piece of fossilized snake skin. Cost me fifty million offline dollars. He said it was a 'catalyst' for a god. When the mountain started glowing an hour ago... I figured out what he meant.”" },
      { type: "prose", text: "Golden dust condensed into a swirling vortex of pure, arrogant light. From it stepped a man of inhuman beauty, crimson eyes surveying the world like a garden he owned, gleaming golden armor radiating ancient majesty." },
      { type: "prose", text: "Gilgamesh. The King of Heroes." },
      { type: "impact", effect: "expand", text: "HOUR 54 TO 57: THE GOLDEN MOCKERY" },
      { type: "dialogue", speaker: "Gilgamesh", variant: "crimson", text: "“To think that the King would be called to a cavern of dirt and wire, summoned by a mongrel whose only claim to power is numbers on a glass screen.”" },
      { type: "dialogue", speaker: "Alistair", variant: "crimson", text: "“Hey. I paid for you! You're my Servant. Kill them!”" },
      { type: "dialogue", speaker: "Gilgamesh", variant: "crimson", text: "“Silence, mongrel. A king does not take orders from a swine who buys his crown with the laughter of fools. Saber. You continue to reject my proposals, yet fate continually places you before my throne. And who is this accompanying you? A faker? A Master who crawls on the floor?”" },
      { type: "dialogue", speaker: "Gilgamesh", variant: "crimson", text: "“You seek to destroy this world over a wounded pride? How utterly mundane. This world is a garden of weeds, yes, but it is my garden. If it is to be pruned, it will be by my hand, not the tantrum of a broken mediator.”" },
      { type: "dialogue", speaker: "Saber", variant: "cyan", text: "“Gilgamesh. Step aside. This Master's cause is absolute. This timeline is forfeit.”" },
      { type: "dialogue", speaker: "Gilgamesh", variant: "crimson", text: "“Absolute? Nothing is absolute but my treasury!”" },
      { type: "prose", text: "The air rippled. Golden portals tore open across the room, ancient Noble Phantasms emerging from the ripples — the original prototypes of every myth in human history." },
      { type: "impact", effect: "glow", text: "The Gate of Babylon." },
      { type: "dialogue", speaker: "Gilgamesh", variant: "crimson", text: "“Let us see if your 'absolute cause' can withstand the weight of human history!”" },
      { type: "impact", effect: "expand", text: "HOUR 58 TO 59: THE RAIN OF DEATH" },
      { type: "prose", text: "He fired. Weapons shot from the golden portals like missiles, breaking the sound barrier in the confined bunker." },
      { type: "dialogue", speaker: "Gurtej", variant: "neutral", text: "“Saber!”" },
      { type: "prose", text: "She stepped into the storm, her invisible blade deflecting a cursed spear, parrying a demonic broadsword, shattering a crystalline halberd. But there were too many." },
      { type: "dialogue", speaker: "Gilgamesh", variant: "crimson", text: "“Is this all the King of Knights can muster? Dance for me, Saber! Show me the limits of your dying ideals!”" },
      { type: "prose", text: "A curved scimitar slipped past her guard, drawing blood. My cousin filmed it, laughing." },
      { type: "dialogue", speaker: "Alistair", variant: "crimson", text: "“See, Gurtej? Money always wins! Even in magic, money buys the best toys!”" },
      { type: "dialogue", speaker: "Gurtej", variant: "neutral", text: "“Saber, fall back!”" },
      { type: "prose", text: "She couldn't. If she moved, the barrage would turn me into a red mist. A blur of red stepped in front of me." },
      { type: "impact", effect: "expand", text: "HOUR 60: THE COUNTER GUARDIAN'S ANSWER" },
      { type: "prose", text: "Archer walked past me, unarmed, straight into the lethal zone." },
      { type: "dialogue", speaker: "Saber", variant: "cyan", text: "“Archer, what are you doing?!”" },
      { type: "dialogue", speaker: "Archer", variant: "cyan", text: "“I'm taking out the trash.”" },
      { type: "dialogue", speaker: "Gilgamesh", variant: "crimson", text: "“You step forward to die, Faker? A nameless dog trying to bite a god?”" },
      { type: "dialogue", speaker: "Archer", variant: "cyan", text: "“You talk too much, your Majesty. You rely on the weight of others' legends because you have none of your own to wield. You aren't a warrior. You're just a very wealthy thief.”" },
      { type: "dialogue", speaker: "Gilgamesh", variant: "crimson", text: "“I will turn you to ash, mongrel!”" },
      { type: "prose", text: "A hundred Noble Phantasms aimed at Archer's chest. He closed his eyes. Blue flame ignited beneath his feet. When he opened them, they burned with the light of a dying star." },
      { type: "impact", effect: "shake", text: "\"I am the bone of my sword. Steel is my body and fire is my blood. I have created over a thousand blades. Unknown to Death, nor known to Life. Have withstood pain to create many weapons. Yet, those hands will never hold anything. So as I pray...\"" },
      { type: "prose", text: "The bunker dissolved. Gears turned in a smog-choked sky. Swords sprouted from cracked, barren earth like rusted grass." },
      { type: "impact", effect: "glow", text: "The Infinite Forge of the Wrought Iron Hero." },
      { type: "prose", text: "The Reality Marble overwrote the Himalayas. We were standing inside the mind of EMIYA — and every single weapon Gilgamesh possessed was already forged, waiting, and aimed directly at the Golden King." }
    ]
  },

  /* ============================ CHAPTER 6 ============================ */
  {
    id: 6,
    title: "The Broken Forge and the World's Betrayal",
    volume: 4,
    synopsis: "The Reality Marble shatters, a hidden Assassin claims its toll, and the King of Knights learns exactly what the world thinks of mercy.",
    content: [
      { type: "impact", effect: "glow", text: "Active Combatants — Saber Artoria: Defending Master · Archer EMIYA: Spirit Core Fracturing · Gilgamesh: Gate of Babylon Active · Master Gurtej: Prana Output Critical" },
      { type: "impact", effect: "expand", text: "HOUR 61 TO 62: THE HOLLOW CLASH" },
      { type: "prose", text: "The sky of Unlimited Blade Works was choked with ash and turning gears. Gilgamesh unleashed the Gate of Babylon; Archer didn't need to trace new blades — they were already here, ripping free of the barren earth to clash mid-flight against the King's treasury." },
      { type: "prose", text: "I didn't notice it then — my cousin's shadow pooling unnaturally against the rusted earth, darker than the smog-choked sky, a whisper of Hassan-i-Sabbah waiting patiently for the King's distraction." },
      { type: "prose", text: "I dropped to my knees, clutching my chest, the toll of the Reality Marble bleeding me dry." },
      { type: "dialogue", speaker: "Archer", variant: "cyan", text: "“Master, stay down! The Grail has fully awakened beneath this mountain. Because you lack Command Seals, it recognizes us as rogue entities. It is restricting my mana intake. I have exactly one hundred and eighty seconds before my Spirit Core collapses and this world shatters!”" },
      { type: "dialogue", speaker: "Saber", variant: "cyan", text: "“Master... the sheer scale of this destruction... I must tell you now. I will protect you to my dying breath. I swore to be your sword. But even if we survive this bunker, I cannot use Excalibur to destroy the Earth. I cannot! There are still innocents out there who know nothing of your pain. I will not let them burn for the sins of the cruel.”" },
      { type: "impact", effect: "expand", text: "HOUR 63: THE EVOLVED SHADOW" },
      { type: "dialogue", speaker: "Alistair", variant: "crimson", text: "“Kill him! Just use the sword that destroys worlds! I command you! Use the Seals!”" },
      { type: "prose", text: "He never finished the incantation. The unnaturally dark shadow cast by his own boots twisted upward — a corrupted Hassan-i-Sabbah, second-stage evolutionary form, a wraith-class anomaly waiting inside his own darkness. Its clawed hand swept upward. His head detached from his shoulders." },
      { type: "dialogue", speaker: "Assassin", variant: "crimson", text: "“...The false master is severed... the shadow claims the toll...”" },
      { type: "prose", text: "Gilgamesh leaped backward, narrowly avoiding a decaying cursed strike. At that exact millisecond, Archer's time limit expired. The sky of gears shattered like a mirror struck by a hammer. The suffocating atmosphere of the Himalayan bunker rushed back into our lungs." },
      { type: "impact", effect: "expand", text: "HOUR 64 TO 65: THE GOLDEN DEPARTURE AND THE VIRAL TRUTH" },
      { type: "prose", text: "Archer landed heavily, coughing crimson blood. Gilgamesh looked down at the decapitated body without anger, only cold amusement." },
      { type: "dialogue", speaker: "Gilgamesh", variant: "crimson", text: "“A King does not mourn a rat who dies in the dark. This farce has lost its entertainment value. I sense a soul upon this mountain far more twisted, far more entertaining than this dead swine. An Overseer who reeks of beautiful tragedy. Survive if you can, Faker. We will finish this when the true war begins.”" },
      { type: "prose", text: "Gilgamesh dissolved into golden particles, abandoning the battlefield to seek out his new Master." },
      { type: "dialogue", speaker: "Gurtej", variant: "neutral", text: "“Archer. Are you...”" },
      { type: "dialogue", speaker: "Archer", variant: "cyan", text: "“Dying. Slowly. Master, the Grail War has officially begun. Without Command Seals, my anchor to this world is tearing. We must find the Overseer of this territory and formalize your contract, or I will fade by dawn.”" },
      { type: "prose", text: "Saber was staring at the floor near the cousin's body. His smartphone. It was still recording — livestreaming to the cloud. The raw footage had already been ripped, clipped, and mirrored across ten thousand servers." },
      { type: "impact", effect: "glow", text: "Breaking — Global Emergency. Superhuman entities confirmed in Himalayan border region. United Nations Security Council authorizes lethal force. Clock Tower masquerade status: COMPROMISED." },
      { type: "prose", text: "The \"Shoe Video\" was gone. In its place, a global state of emergency. We were no longer a meme. We were a planetary target." },
      { type: "impact", effect: "expand", text: "HOUR 66: THE TOWN OF TRAITORS" },
      { type: "prose", text: "We fled the bunker before dawn, detouring into a populated Himalayan border town for medical supplies. Saber and Archer dematerialized their armor. I pulled a hood low." },
      { type: "dialogue", speaker: "Civilian", variant: "neutral", text: "“It's him! The terrorist from the video! The freak with the monsters!”" },
      { type: "prose", text: "The marketplace went dead silent, then greed and fear took over. A mob of fifty surrounded us with iron pipes and stones." },
      { type: "dialogue", speaker: "Saber", variant: "cyan", text: "“Stop this! We do not wish to harm you!”" },
      { type: "prose", text: "She refused to draw her sword, taking the brunt of the blows bare-handed. Then the chopping sound of helicopter blades drowned out the mob." },
      { type: "impact", effect: "expand", text: "HOUR 67: THE SLAUGHTER OF THE INNOCENTS" },
      { type: "prose", text: "Three military gunships crested the ridge. The civilians cheered, thinking their protectors had arrived." },
      { type: "dialogue", speaker: "Commander", variant: "crimson", text: "“Targets acquired. The anomalies have engaged the civilian populace. Weapons free! Eradicate the crowd, but secure the anomalies alive. R&D wants the dimensional technology intact. Fire!”" },
      { type: "prose", text: "The gunships opened fire on the crowd itself — collateral damage to frame us." },
      { type: "dialogue", speaker: "Saber", variant: "cyan", text: "“NO!”" },
      { type: "prose", text: "She threw herself over a boy and his mother. The mother was caught in the blast, killed instantly. Saber knelt in bloody snow, shielding the boy, reaching a bloodstained hand toward him." },
      { type: "dialogue", speaker: "Boy", variant: "neutral", text: "“Monster! You brought the metal birds! You killed her! I curse you! Demon! Demon!”" },
      { type: "prose", text: "A sniper round took the boy's life mid-curse." },
      { type: "dialogue", speaker: "Squad Leader", variant: "crimson", text: "“Hostiles surrounded. Engaging the Silver Demon.”" },
      { type: "prose", text: "Saber stood. She didn't grant them the honor of a Knight's strike. In less than three seconds she was among them, tearing through exosuits like wet paper. When the last body hit the ground, Archer tossed a stripped military tablet to my feet, its screen glowing with the live global feed." },
      { type: "impact", effect: "glow", text: "Breaking — Massacre Confirmed. Full border town slaughtered by \"Hell's Army.\" UN authorizes global lethal force against anomalies designated VARDILORD · SILVER FIEND · RED DEVIL. Kill on sight." },
      { type: "prose", text: "The internet had already given us our titles. I was Vardilord, the Demon King. The world was uniting to hunt us down, entirely blind to the fact that their own governments had orchestrated the massacre." },
      { type: "prose", text: "Saber stood amidst the carnage, painted in the blood of soldiers and the civilians she had failed to save. I watched the light die in her eyes." },
      { type: "dialogue", speaker: "Saber", variant: "cyan", text: "“There is no one left to save. Give the order. Let it burn.”" },
      { type: "impact", effect: "glow", text: "The King of Knights has abandoned her oath." }
    ]
  },

  /* ============================ CHAPTER 7 ============================ */
  {
    id: 7,
    title: "The Blood of the Mountain and the Overseer's Secret",
    volume: 4,
    synopsis: "A hidden monastery, an old friend in a Church cassock, and the rules of the Grail War rewritten in blood and Black Keys.",
    content: [
      { type: "impact", effect: "expand", text: "HOUR 68: THE LORD'S DECREE" },
      { type: "dialogue", speaker: "Saber", variant: "cyan", text: "“Let it burn.”" },
      { type: "prose", text: "She drove her invisible blade into the blood-soaked snow instead of invoking Excalibur's true name — that would vaporize the mountain and the last of my life force." },
      { type: "dialogue", speaker: "Saber", variant: "cyan", text: "“Strike Air.”" },
      { type: "prose", text: "A pressurized column of solid kinetic force slammed into the underbelly of the lead gunship, crumpling it like a soda can. The other two banked hard, turrets tracking her — but the guns never fired. A cold, aristocratic voice cut through the wind." },
      { type: "dialogue", speaker: "Lord", variant: "crimson", text: "“Stand down, dogs. You are out of your depth, mundane fools. You are firing blind into the abyss of Mystery. Withdraw your toys. This territory is now under the absolute jurisdiction of the Mage's Association.”" },
      { type: "prose", text: "The gunships retreated, fleeing as if they'd looked into the eyes of a predator. Behind me, Archer collapsed." },
      { type: "impact", effect: "expand", text: "HOUR 69: THE BLEEDING TREK" },
      { type: "prose", text: "His skin was fracturing like porcelain, tiny motes of blue ether leaking from the cracks. His Spirit Core was shattering." },
      { type: "dialogue", speaker: "Archer", variant: "cyan", text: "“The... Reality Marble... It drained the last of my anchor. I am dissolving, Master.”" },
      { type: "dialogue", speaker: "Gurtej", variant: "neutral", text: "“No. Not yet. You don't get to die here.”" },
      { type: "dialogue", speaker: "Saber", variant: "cyan", text: "“Master, he needs a leyline convergence. A Spirit Vein. And we need an Overseer.”" },
      { type: "dialogue", speaker: "Archer", variant: "cyan", text: "“I can... feel it. A massive pool of mana... an artificial bounded field. A sanctuary.”" },
      { type: "prose", text: "We dragged him through two agonizing hours of blizzard. At the end, hidden from satellite view by ancient magecraft, stood a massive, snow-covered stone monastery. I kicked the doors open." },
      { type: "impact", effect: "expand", text: "HOUR 70: THE COLLEGE BESTIE" },
      { type: "prose", text: "Warm inside, lit by hundreds of candles, an Overseer in Holy Church Burial Agency robes spun around, three Black Keys already materialized between his fingers. He looked at the dying man in red, the silver-armored Knight, then at me. The Black Keys clattered to the floor." },
      { type: "dialogue", speaker: "Overseer", variant: "cyan", text: "“...Gurtej?”" },
      { type: "dialogue", speaker: "Gurtej", variant: "neutral", text: "“Jaskaran?! What the hell are you doing here?!”" },
      { type: "dialogue", speaker: "Jaskaran", variant: "cyan", text: "“What am I doing here?! Bro! I was literally texting you yesterday about our BBA Financial Management assignment! Why weren't you answering your phone?! And why is the news calling you the Demon King Vardilord?!”" },
      { type: "dialogue", speaker: "Gurtej", variant: "neutral", text: "“My cousin broke my shoe and posted it online! It's a long story! Why are you wearing a wizard robe?!”" },
      { type: "dialogue", speaker: "Jaskaran", variant: "cyan", text: "“It's a Church cassock, you idiot! My family belongs to a hidden lineage of the Holy Church! I was stationed in Ludhiana to live a normal life and monitor the regional leylines! When your stupid shoe-video sparked a massive surge of True Ether, the Church recalled me here to act as the official Grail War Overseer!”" },
      { type: "dialogue", speaker: "Saber", variant: "cyan", text: "“Master... you know the Overseer?”" },
      { type: "dialogue", speaker: "Gurtej", variant: "neutral", text: "“He's my college best friend!”" },
      { type: "dialogue", speaker: "Archer", variant: "cyan", text: "“Fate... has a sick sense of humor.”" },
      { type: "prose", text: "His knees buckled. He collapsed, semi-transparent. Jaskaran's demeanor shifted instantly — panicked student to cold, calculated Executor." },
      { type: "dialogue", speaker: "Jaskaran", variant: "cyan", text: "“His Spirit Core is collapsing. He doesn't have an anchor. Give me your right hand.”" },
      { type: "impact", effect: "expand", text: "HOUR 71: THE RITUAL OF THE SAINT GRAPH" },
      { type: "prose", text: "Jaskaran gripped my wrist, chanting rapid Latin. A branding pain ignited on the back of my hand — three jagged, blood-red marks shaped like a burning crown." },
      { type: "dialogue", speaker: "Jaskaran", variant: "cyan", text: "“Command Seals transferred from the Overseer's reserve. You are officially a Master in this War. But it's not enough. You don't have the Magic Circuits to sustain two top-tier Servants. If I don't alter their Saint Graphs right now, Archer dies, and Saber will drain your life force until your heart stops.”" },
      { type: "dialogue", speaker: "Gurtej", variant: "neutral", text: "“Do it. Whatever it takes.”" },
      { type: "dialogue", speaker: "Jaskaran", variant: "cyan", text: "“Archer first. I'm going to forcibly stitch his Spirit Core to the Himalayan Spirit Vein directly beneath this church. Option A: Leyline Anchoring.”" },
      { type: "prose", text: "He drove four Black Keys into the floor around Archer, channeling the raw mana of the mountain up through the stone. Archer screamed as a mythological soul was violently rewritten." },
      { type: "dialogue", speaker: "Jaskaran", variant: "cyan", text: "“He's stabilized. But there's a catch, Gurtej. He's tethered to the mountain now. Unlimited mana to project his weapons, but if he leaves the Himalayan range, the tether snaps and he dies instantly. Your ultimate sniper — bound to this base.”" },
      { type: "dialogue", speaker: "Archer", variant: "cyan", text: "“A guard dog for the Demon King. Fitting.”" },
      { type: "dialogue", speaker: "Jaskaran", variant: "cyan", text: "“Saber's turn. I can't anchor you both. Option B.”" },
      { type: "prose", text: "He retrieved a crystalline vial of pulsing crimson liquid — a drop of the original Grail's mud." },
      { type: "dialogue", speaker: "Jaskaran", variant: "cyan", text: "“An elixir of incarnation. Saber, if you drink this, you will cease to be a spirit. You will be granted a true, physical body. You won't drain Gurtej's mana anymore. You will generate your own energy. You will need to eat, sleep, and breathe like a human.”" },
      { type: "dialogue", speaker: "Saber", variant: "cyan", text: "“I failed them as a spirit. Perhaps I will be a better weapon as a mortal.”" },
      { type: "prose", text: "She drank it in a single motion. The faint ethereal glow around her vanished. Then, silence. Then — a heartbeat. She dropped to her knees, shivering, feeling cold for the first time in her legendary life. The King of Knights was flesh and blood." },
      { type: "impact", effect: "glow", text: "Archer (EMIYA) — Leyline Anchored, Range Restricted, Mana Infinite · Saber (Artoria) — Flesh Incarnation, Prana Cost Zero, State Mortal" },
      { type: "impact", effect: "expand", text: "HOUR 72: THE NEW BOARD" },
      { type: "dialogue", speaker: "Jaskaran", variant: "cyan", text: "“You guys need to understand the reality of the board. The entire world thinks you are a superhuman terrorist organization. The UN is mobilizing conventional armies. But they are the least of your worries.”" },
      { type: "prose", text: "He spread classified dossiers across the stone floor." },
      { type: "dialogue", speaker: "Jaskaran", variant: "cyan", text: "“The Clock Tower. The elite Magus families are furious that you broke the masquerade. They don't want to kill you; they want to capture Saber and Archer alive, dissect them, and study their dimensional technology to reach the Root. The Burial Agency, my bosses, view your Reality Marble and the viral footage as ultimate heresy — they will send Assassins to erase you. And worst of all, Gurtej... because you forced the Grail to awaken, it had to balance the scales. The global war has officially begun. The Grail has chosen other Masters around the world. Seven Servants total.”" },
      { type: "dialogue", speaker: "Gurtej", variant: "neutral", text: "“Gilgamesh.”" },
      { type: "dialogue", speaker: "Jaskaran", variant: "cyan", text: "“Yes. The King of Heroes has forged a contract with a new Master somewhere in the world. And that 2nd-stage Assassin is roaming free. You are public enemy number one, and you are surrounded by monsters.”" },
      { type: "prose", text: "The mediator who walked into a Ludhiana banquet hall three days ago was dead." },
      { type: "dialogue", speaker: "Gurtej", variant: "neutral", text: "“Let them come. We have a mountain to hold, and a world to burn.”" }
    ]
  },

  /* ============================ CHAPTER 8 ============================ */
  {
    id: 8,
    title: "The Psychopath Pact and the Planet's Immune System",
    volume: 4,
    synopsis: "Instant noodles, a blood oath between two college dropouts, and the terrifying shape of what the Earth sends when it decides to fight back.",
    content: [
      { type: "impact", effect: "expand", text: "HOUR 73: THE KING'S FIRST MEAL" },
      { type: "prose", text: "The Himalayan wind howled against the monastery doors, but inside, the war of gods and kings was momentarily suspended by the screech of a cheap portable gas stove. Jaskaran, still in his heavy Executor cassock, poured boiling water into three styrofoam cups of instant noodles." },
      { type: "prose", text: "Saber took hers hesitantly, wrapped in a wool blanket, shivering for the first time since I'd summoned her. She took a bite. Her emerald eyes widened slightly. Not a grand feast of Camelot — cheap, sodium-filled college food. But to a spirit who had lived centuries as nothing but a weapon, the warmth spreading through her chest was overwhelming. She said nothing. She just kept eating, holding the cup like a lifeline." },
      { type: "dialogue", speaker: "Jaskaran", variant: "cyan", text: "“You know... we had that PTU fourth-semester exam tomorrow. Financial Management. I hadn't even opened the syllabus.”" },
      { type: "dialogue", speaker: "Gurtej", variant: "neutral", text: "“Yeah. I guess we're dropping out of GNIMT.”" },
      { type: "dialogue", speaker: "Jaskaran", variant: "cyan", text: "“Honestly? Thank God. I hated that class anyway.”" },
      { type: "impact", effect: "expand", text: "HOUR 74: THE PSYCHOPATH PACT" },
      { type: "dialogue", speaker: "Jaskaran", variant: "cyan", text: "“Gurtej. When we were walking up here, you said you wanted to wipe the board clean. Were you just talking, or did you mean it?”" },
      { type: "dialogue", speaker: "Gurtej", variant: "neutral", text: "“The Magi, the politicians, the Church... they're all corrupt. If we win this Grail, I'm not wishing for money or a reset. I want to erase it all.”" },
      { type: "prose", text: "I waited for the righteous Executor to draw his blades. I waited for my best friend to tell me I had lost my mind." },
      { type: "dialogue", speaker: "Jaskaran", variant: "cyan", text: "“Valid.”" },
      { type: "dialogue", speaker: "Gurtej", variant: "neutral", text: "“Valid? That's it?”" },
      { type: "dialogue", speaker: "Jaskaran", variant: "cyan", text: "“Bro, I've worked for the Burial Agency for three years. Do you know the kind of sick, twisted garbage the Magus families do behind closed doors? Do you know how much blood the Church spills just to keep the 'masquerade' intact? The world is a meat grinder. If you want to break the wheel, I'm with you.”" },
      { type: "prose", text: "Two college dropouts, sitting in a freezing church, casually agreeing to global annihilation." },
      { type: "impact", effect: "glow", text: "Blood Oath Registered — The Psychopath Pact. To prune this corrupted timeline from the Tree of Time. Gurtej, Master · Projection Magus. Jaskaran, Overseer · Executor." },
      { type: "dialogue", speaker: "Jaskaran", variant: "cyan", text: "“But... you can't just blow up the Earth with Excalibur. To rewrite reality, you have to win the Holy Grail War. We have to kill Gilgamesh, the Assassin, and whoever else the Grail summoned.”" },
      { type: "impact", effect: "expand", text: "HOUR 75: THE FORGE AWAKENS" },
      { type: "dialogue", speaker: "Gurtej", variant: "neutral", text: "“Then we need to split our forces. I have two contracts. It's too much of a target. You need to take Archer.”" },
      { type: "dialogue", speaker: "Archer", variant: "cyan", text: "“A Master transfer. Tactical. I have no objections, provided this fake priest can supply the mana.”" },
      { type: "dialogue", speaker: "Jaskaran", variant: "cyan", text: "“I'm anchoring you to the mountain's leyline, you arrogant bastard. You'll have infinite mana. You stay here, defend the church, and cover us with long-range Broken Phantasms. Gurtej and Saber will be the vanguard.”" },
      { type: "impact", effect: "glow", text: "Command Seal Transfer — Gurtej (Former Master) → Archer (Servant) → Jaskaran (New Master). Transfer Complete — Bond Established." },
      { type: "prose", text: "The moment the spiritual connection snapped, a violent heat exploded up my right arm. The air tasted heavy — ozone and rusted iron. Neon-green lines of magical circuitry burned themselves permanently into my flesh." },
      { type: "dialogue", speaker: "Archer", variant: "cyan", text: "“The Reality Marble... Because the Grail forced my forge open using his life force, my Magecraft didn't just drain him. It burned an imprint into his soul.”" },
      { type: "prose", text: "I raised my glowing right hand." },
      { type: "impact", effect: "shake", text: "\"Trace — On.\"" },
      { type: "impact", effect: "glow", text: "Magic Circuit Activation — 27 circuits detected. Structural Grasp / Projection." },
      { type: "prose", text: "A flash of blue light, and the weight of solid steel dropped into my grip — a perfectly replicated, nameless wrought-iron broadsword." },
      { type: "impact", effect: "glow", text: "Gurtej (Vardilord) — Circuits Awakened. Origin: Sword. Affinity: Projection." },
      { type: "impact", effect: "expand", text: "HOUR 76: THE MASTERMIND PLAY" },
      { type: "dialogue", speaker: "Jaskaran", variant: "cyan", text: "“Okay. Okay, this changes things. With Saber unsealed as a mortal and you wielding Projection magic, you guys can actually fight. But we need to thin the herd before you leave. As the Overseer, the other Masters are required to report to me. I'm going to play the terrified, neutral priest. When the Masters of Berserker and the High Assassin contact the Church, I'll 'accidentally' leak Gilgamesh's coordinates. I'll convince them the Golden King is the ultimate threat. Let the monsters tear each other apart while I sit here drinking coffee.”" },
      { type: "dialogue", speaker: "Archer", variant: "cyan", text: "“Devious. You truly are fit for the Holy Church.”" },
      { type: "impact", effect: "expand", text: "HOUR 77: THE PLANET'S IMMUNE SYSTEM" },
      { type: "dialogue", speaker: "Gurtej", variant: "neutral", text: "“So Gilgamesh is dealt with for now. What's the final boss?”" },
      { type: "dialogue", speaker: "Jaskaran", variant: "cyan", text: "“The Earth itself. Listen to me carefully. Imagine the planet Earth is a human body. Right now, humanity is like a virus living on that body. The UN armies, the Clock Tower Magi... they are just a fever. They are human problems. But if we actually get close to winning the Grail... if we actually try to erase humanity... the Earth has an immune system. It's an unconscious will called Alaya. And when Alaya senses that a threat is going to destroy the world, it deploys its white blood cells. The Counter Force.”" },
      { type: "impact", effect: "glow", text: "Global Threat Assessment — London: Clock Tower HQ, Extreme. Rome: Burial Agency Kill Teams, Hostile. Himalayas: Monastery Base, Allied. Unknown: Gilgamesh's new Master, Unknown." },
      { type: "dialogue", speaker: "Jaskaran", variant: "cyan", text: "“They aren't normal heroes. They are nameless, faceless executioners crowned by the planet itself. They are summoned with one absolute directive: erase the anomaly. If we push this too far, the Earth will literally summon a god to execute us. It is a statistically impossible fight.”" },
      { type: "dialogue", speaker: "Gurtej", variant: "neutral", text: "“Let the Earth send its executioners.”" },
      { type: "dialogue", speaker: "Saber", variant: "cyan", text: "“What is our target, Master?”" },
      { type: "dialogue", speaker: "Gurtej", variant: "neutral", text: "“The Clock Tower thinks they can hunt us with Enforcers. We're going to London to burn the Mage's Association to the ground.”" }
    ]
  },

  /* ============================ CHAPTER 9 ============================ */
  {
    id: 9,
    title: "The Mortal King and the Memory Maze",
    volume: 5,
    synopsis: "London's fog, a memory bounded field built from old wounds, and a Black Dog guarding the last door before the Clock Tower.",
    content: [
      { type: "impact", effect: "expand", text: "HOUR 84: FISH AND CHIPS IN THE FOG" },
      { type: "prose", text: "The flight from the Himalayas to London was a blur of forged documents and Church-funded private charters. Now the thick fog of the English capital clung to our clothes. For thirty seconds, the world was still." },
      { type: "prose", text: "Saber, wrapped in a heavy wool trench coat, ate fish and chips from a greasy newspaper cone. She had lived centuries as an immortal spirit construct. She had never felt the biting cold of the fog, or the hollow ache of a mortal stomach. When she looked at me, the rigid kingly stoicism in her eyes was gone. She was human." },
      { type: "dialogue", speaker: "Gurtej", variant: "neutral", text: "“Ready?”" },
      { type: "dialogue", speaker: "Saber", variant: "cyan", text: "“Lead the way, Master.”" },
      { type: "prose", text: "We stepped over the rusted chain-link fence and descended into the pitch-black maw of the abandoned Tube station." },
      { type: "impact", effect: "expand", text: "HOUR 85: THE SINS OF THE ARCHER" },
      { type: "prose", text: "The moment our boots hit the platform, the air pressure dropped. My ears popped painfully. The damp smell of the subway vanished, replaced by the sterile, metallic scent of ozone. The tiled walls began to subtly stretch and curve. Gravity felt tilted." },
      { type: "impact", effect: "glow", text: "WARNING: SPATIAL DISTORTION" },
      { type: "dialogue", speaker: "Overseer", variant: "cyan", text: "“Bounded Field activated. You just crossed the threshold. The Clock Tower knows you're there. I'm reading massive spatial distortions.”" },
      { type: "dialogue", speaker: "Archer", variant: "cyan", text: "“Stop. The third tile on your left is a pressure trigger. Step over it. Take the right fork.”" },
      { type: "dialogue", speaker: "Gurtej", variant: "neutral", text: "“How do you know that?”" },
      { type: "prose", text: "A heavy, static-filled silence on the radio." },
      { type: "dialogue", speaker: "Archer", variant: "cyan", text: "“Master... I have been to this exact bounded field before. Not as your Servant. I was summoned here by the World as a Counter Guardian, centuries from now. The Clock Tower ordered a purge of a rogue faction hiding in these tunnels. I killed fourteen people in this maze. Three of them were children. I know where the traps are because I used them to slaughter Magi. Take the right fork.”" },
      { type: "dialogue", speaker: "Overseer", variant: "cyan", text: "“...Bro.”" },
      { type: "dialogue", speaker: "Archer", variant: "cyan", text: "“Don't. Just walk.”" },
      { type: "impact", effect: "expand", text: "THE MENTAL AMBUSH" },
      { type: "prose", text: "We took the right fork. The tiled walls of the Underground vanished — a warm, golden chandelier glow, the scent of jasmine perfume, a polished marble floor. Six hundred faceless guests laughing in slow motion. The shoe was on the floor, broken." },
      { type: "dialogue", speaker: "Clock Tower Lord", variant: "crimson", text: "“A fascinating catalyst, Mr. Singh. The Bounded Field reads the mind's deepest traumas. You want to burn the world because of this room. We don't care about the world. We only care about reaching the Root. So, I will make you an offer. Leave the Servant. Let us dissect File ART-001. A flesh-incarnated Heroic Spirit is the scientific breakthrough of the millennium. Give her to us, and the Mage's Association will let you walk out of London alive.”" },
      { type: "prose", text: "Through the illusion, Saber met my eyes. The smallest, almost imperceptible nod. She was willing to be sacrificed so I could survive." },
      { type: "dialogue", speaker: "Gurtej", variant: "neutral", text: "“She isn't a weapon anymore. She's my Knight.”" },
      { type: "dialogue", speaker: "Clock Tower Lord", variant: "crimson", text: "“Pity.”" },
      { type: "impact", effect: "expand", text: "HOUR 86: THE HARD LIMIT" },
      { type: "impact", effect: "shake", text: "SHATTER." },
      { type: "prose", text: "The illusion broke like glass. Back in the freezing tunnel. A shadow detached from the ceiling directly above Saber — a Clock Tower Enforcer in anti-magic-rune Kevlar, dropping straight down with a vibrating shortsword aimed at her neck." },
      { type: "impact", effect: "shake", text: "\"Trace — On.\"" },
      { type: "prose", text: "A broadsword formed in my grip. The moment it touched the Enforcer's blade, it shattered into digital blue dust — his weapon was a Mystic Code designed to nullify projection magecraft." },
      { type: "impact", effect: "glow", text: "CRITICAL ERROR: CIRCUIT REJECTION" },
      { type: "prose", text: "Blinding agony ripped through my chest. I fell to my knees, coughing blood onto the subway tracks." },
      { type: "dialogue", speaker: "Overseer", variant: "cyan", text: "“Gurtej, stop! Your circuits are new! You're forcing a newborn engine to redline! If you push past three projections, you WILL have a stroke!”" },
      { type: "dialogue", speaker: "Gurtej", variant: "neutral", text: "“How many have I done?!”" },
      { type: "dialogue", speaker: "Overseer", variant: "cyan", text: "“Two and a half!”" },
      { type: "impact", effect: "glow", text: "Projection Capacity 0.5 / 3.0 — Next projection risks cerebral hemorrhage" },
      { type: "prose", text: "The Enforcer pivoted to execute Saber, whose human reflexes were a fraction too slow to dodge. I threw my bleeding hand forward." },
      { type: "impact", effect: "shake", text: "\"Rho Aias.\"" },
      { type: "impact", effect: "glow", text: "Noble Phantasm — Projected Fragment. Integrity: 12%, cracks propagating." },
      { type: "prose", text: "A single fractured petal formed. The Enforcer's blade slammed into it. It cracked, spider-webbing instantly — but held. It held just long enough. Master protects Servant." },
      { type: "dialogue", speaker: "Clock Tower Enforcer", variant: "crimson", text: "“File ART-001. You're slower than the legends.”" },
      { type: "impact", effect: "glow", text: "Top Secret File: ART-001. Subject: Artoria Pendragon. Class: Saber. Status: INCARNATED — ANOMALY." },
      { type: "prose", text: "The shield shattered, but Saber was already moving. Her Dragon Core unsealed. A visible shockwave of golden Prana burst from her mortal body. She drove her invisible blade forward with the force of a freight train." },
      { type: "impact", effect: "shake", text: "BOOM." },
      { type: "prose", text: "The Enforcer was thrown backward, obliterating the brick wall behind him." },
      { type: "dialogue", speaker: "Gurtej", variant: "neutral", text: "“You're shaking.”" },
      { type: "dialogue", speaker: "Saber", variant: "cyan", text: "“I am cold.”" },
      { type: "dialogue", speaker: "Gurtej", variant: "neutral", text: "“That's not cold. That's adrenaline. Welcome to being human.”" },
      { type: "impact", effect: "expand", text: "HOUR 87: THE ANCIENT GUARD DOG" },
      { type: "prose", text: "The temperature in the tunnel plummeted — not the natural chill of the Underground, but the freezing, paralyzing cold of a predator entering the room." },
      { type: "impact", effect: "glow", text: "SIGNAL LOST. [STATIC]" },
      { type: "prose", text: "The shadows pooled and rose, forming a massive, hulking shape blocking the path. Two burning red eyes opened in the pitch black. The Clock Tower had bound a Phantasmal Beast to guard their gates. The Black Dog of English myth. A corrupted Barghest." },
      { type: "prose", text: "Saber gripped her invisible sword, hands still shaking from adrenaline. She stepped between me and the glowing red eyes and said the one word she had never spoken in her entire legendary life." },
      { type: "dialogue", speaker: "Saber", variant: "cyan", text: "“Run.”" }
    ]
  },

  /* ============================ CHAPTER 10 ============================ */
  {
    id: 10,
    title: "The Heavy Sword and the Desync",
    volume: 5,
    synopsis: "A King learning to fight in a body that bruises, a scalpel thrown between a puppet and its strings, and the vault beneath London finally unlocking.",
    content: [
      { type: "impact", effect: "expand", text: "HOUR 87: THE TACTICAL RETREAT" },
      { type: "prose", text: "The King of Knights didn't charge. She grabbed the collar of my jacket and pulled me into the dark. We hit a dead sprint down a narrow maintenance tunnel, the guttural growl of the Barghest echoing behind us." },
      { type: "dialogue", speaker: "Gurtej", variant: "neutral", text: "“Why are we running? You just blasted an Enforcer through a brick wall. You can obliterate that hound!”" },
      { type: "dialogue", speaker: "Archer", variant: "cyan", text: "“—tej! Master, do you copy?! She can't fight it head-on right now. Her raw power hasn't dropped, but her vessel is flesh and bone. She doesn't have a spirit's weightlessness or automatic shock absorption anymore.”" },
      { type: "dialogue", speaker: "Overseer", variant: "cyan", text: "“She's basically driving a hypercar with no power steering, bro!”" },
      { type: "dialogue", speaker: "Archer", variant: "cyan", text: "“If she unleashes a full-strength Prana Burst right now, the kinetic kickback will cause severe structural recoil to her physical form. She has a micro-delay in her muscle response. She has to calibrate to gravity. Tell her to—”" },
      { type: "impact", effect: "glow", text: "SIGNAL LOST. [STATIC]" },
      { type: "impact", effect: "expand", text: "HOUR 88: CALIBRATION IN THE DARK" },
      { type: "prose", text: "We broke into a subterranean generator room, thick with the smell of rust and ozone. Saber closed her eyes and ran diagnostics on her own humanity — adjusting her footing by a fraction of a centimeter, testing the friction of the air, feeling the heavy, unfamiliar pull of mortal muscle. For a Knight who had never missed a strike in a thousand years, the realization that her body was slightly out of sync must have been terrifying. But she wasn't panicking. She was adapting." },
      { type: "prose", text: "Then the eastern wall crumbled. The Barghest shouldered through the gap — matted black fur, calcified bone plates. It wasn't alone. A Clock Tower Magus walked calmly through the rubble, violet threads of magical energy plunging into the Barghest's spine, his footsteps landing in exact rhythm with the Hound's massive paws. A twisted Demi-Servant fusion." },
      { type: "impact", effect: "glow", text: "Threat Assessment — Synchronized. Controller: Clock Tower Enforcer, Puppet Master. Vessel: Barghest, Phantasmal Beast. Treat as single target." },
      { type: "prose", text: "The Barghest lunged. Saber parried." },
      { type: "impact", effect: "shake", text: "CRACK." },
      { type: "prose", text: "Her footing was a fraction of a degree off. The shock traveled up her arms; she was pushed back two full steps. The Magus flicked his fingers, and the beast pivoted with impossible agility from a blind angle. Every time she adjusted, he shifted the puppet strings. They were going to overwhelm her." },
      { type: "impact", effect: "glow", text: "Projection Capacity 0.5 / 3.0 — Final projection, cerebral hemorrhage imminent." },
      { type: "prose", text: "Half a projection. Barely enough to trace a butter knife. But I didn't need a sword. I needed a scalpel." },
      { type: "impact", effect: "shake", text: "\"Trace — On.\"" },
      { type: "impact", effect: "glow", text: "Projection — Holy Sacrament. Black Key. Integrity: Unstable, 2s to dissolution." },
      { type: "prose", text: "The Black Key that formed in my grip was warped, flickering. It would dissolve in two seconds. Two seconds was enough. I didn't aim at the beast, or the Magus. I aimed at the space between them — the exact point where the violet puppet threads converged into the Barghest's spinal column." },
      { type: "prose", text: "Saber saw my arm move. In flawless, silent chemistry, she feinted left, drawing the Barghest a half-degree off-center, exposing the threads for exactly one heartbeat." },
      { type: "prose", text: "I threw the Black Key. It struck the convergence point and detonated — not with fire, but with pure conceptual rejection. The violet threads whipped back like severed power lines. The Magus screamed, grasping his head as neural feedback hit him like a freight train. The Barghest stumbled, losing its guiding intelligence." },
      { type: "impact", effect: "glow", text: "Threat Assessment — Desynced. Controller: Incapacitated. Vessel: Unguided, survival instinct only. Link severed." },
      { type: "impact", effect: "expand", text: "HOUR 89: NEWTON'S THIRD LAW" },
      { type: "prose", text: "Saber moved. It was the ugliest strike I had ever seen from the King of Knights — no flowing elegance, no golden arc of Camelot's finest swordsmanship. Just raw, desperate, physical weight. She planted her boots wide and swung the invisible blade into the Barghest's left shoulder." },
      { type: "impact", effect: "shake", text: "CRACK." },
      { type: "prose", text: "Mortal kinetic force grinding against calcified bone. The beast howled, black ichor spraying, its front leg buckling. But Newton's third law didn't care about legends. The recoil hit Saber instantly — I heard the bones in her wrists pop under the strain. She staggered, boots skidding on blood-slicked floor, her face contorting in genuine, searing human pain." },
      { type: "impact", effect: "glow", text: "Servant Status: ART-001 — Mortal Vessel. Wrist Integrity: Compromised. Motor Function: Degraded, Micro-delay Active." },
      { type: "prose", text: "She locked her knees, drove her sword into the ground like a crutch, and held herself upright through pure, grinding willpower. Critically injured and its puppet strings broken, the Barghest dragged itself into the shadows. The Magus cast a frantic retreat glyph, and the darkness swallowed them both." },
      { type: "prose", text: "My legs gave out. A blinding supernova exploded behind my eyes." },
      { type: "impact", effect: "glow", text: "Projection System 0.0 / 3.0 — System Shutdown. All Circuits Dark." },
      { type: "prose", text: "I heard Saber's heavy, uneven footsteps as she walked over and dropped to one knee. Her wrists were already bruising deep purple. Her breathing was ragged — the breathing of a woman who had just discovered what physical exhaustion felt like. She reached out and gripped my shoulder, her hand shaking but her grip iron." },
      { type: "dialogue", speaker: "Saber", variant: "cyan", text: "“We held.”" },
      { type: "prose", text: "Not we won. Just — we held. We survived. We're still here." },
      { type: "dialogue", speaker: "Gurtej", variant: "neutral", text: "“Your grip is going to leave a bruise.”" },
      { type: "prose", text: "The corner of her mouth twitched — the smallest, most fragile hint of something that, in another life, might have been a smile." },
      { type: "dialogue", speaker: "Saber", variant: "cyan", text: "“Good.”" },
      { type: "prose", text: "Then a sound interrupted us. Deep beneath us, a massive, ancient mechanical grinding shook the foundation of the room. The vault doors to the Clock Tower's true underground labyrinth — the Spiritual Tomb of Albion — were unlocking." },
      { type: "prose", text: "The path to the Lord was finally open. And I didn't have a single drop of magic left." }
    ]
  },

];
